List<String> phrases = [
  'Username',
  'Password',
  'Login',
  'Home',
  'Back',
  'Register',
  'Search',
  'Deworming',
  'Immunization',
  'Growth',
  'HIV/EID',
  'Tuberculosis',
  'Sync',
  'Logout',
  'Patient Information',
  'Register Patient',
  'Sex at birth',
  'female',
  'male',
  'Date of Birth',
  'Neighborhood',
  'Relationship',
  'Family Name',
  'Other Names',
  'cannot be future date',
];
