List<String> phrases = [
  'Username',
  'Password',
  'Login',
  'Home',
  'Back',
  'Register',
  'Search',
  'Deworming',
  'Immunization',
  'Growth',
  'HIV/EID',
  'Tuberculosis',
  'Sync',
  'Logout',
  'Patient Information',
  'Register Patient',
  'Sex at birth',
  'female',
  'male',
  'Date of Birth',
  'Neighborhood',
  'Relationship',
  'Family Name',
  'Other Names',
  'Cannot be future date',
  'Register Patient',
  'Enter family name',
  'Enter other names',
  'Please select neighborhood',
  'Please select birthdate',
  'Please select sex',
  'Patient Contacts',
  'mother',
  'grandmother',
  'aunt',
  'sister',
  'father',
  'grandfather',
  'uncle',
  'brother',
  'other',
  'Name',
  'Birthdate',
  'Sex',
  'Search Name',
  'Register New Patient',
];
