name: vigor
description: mHealth Platform, utilizing FHIR, written in Dart/Flutter to create
  transcendent data

publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  auto_size_text: ^2.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  fhir: ^0.4.0
  fhir_db: ^0.3.0-nullsafety.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_sheet_localization:
    git:
      url: git://github.com/Dokotela/flutter_sheet_localization.git
      path: flutter_sheet_localization
  flutter_svg: ^0.21.0-nullsafety.0
  freezed_annotation: ^0.14.1
  get: ^4.0.0-nullsafety.2
  get_storage: ^2.0.1
  google_fonts: ^2.0.0
  http: ^0.13.0
  in_date_utils: ^1.0.1-nullsafety.0
  intl: ^0.17.0
  path_provider: ^2.0.1
  photo_view: ^0.11.1
  responsive_builder: ^0.3.0
  simple_tooltip: ^0.1.16
  table_sticky_headers: ^2.0.0
  timeago: ^3.0.2
  translator: ^0.1.6+1

dev_dependencies:
  build_runner: ^1.10.2
  flutter_sheet_localization_generator:
    git:
      url: git://github.com/Dokotela/flutter_sheet_localization.git
      path: flutter_sheet_localization_generator
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1
  lint: ^1.3.0

dependency_overrides:
  build: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/flags/
    - assets/img/
    - assets/svg/
