name: vigor
description: mHealth Platform, utilizing FHIR, written in Dart/Flutter to create
  transcendent data

publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.8.4 <3.0.0'

dependencies:
  auto_size_text: ^2.1.0
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  date_utils: ^0.1.0
  fhir: ^0.2.1
  fhir_db: ^0.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_sheet_localization: ^2.0.1
  flutter_svg: ^0.19.1
  freezed_annotation: ^0.12.0
  get: ^3.24.0
  get_storage: ^1.4.0
  google_fonts: ^1.1.2
  http: ^0.12.2
  intl: ^0.16.1
  path_provider: ^1.6.27
  photo_view: ^0.10.3
  simple_tooltip: ^0.1.16
  table_sticky_headers: ^1.2.0
  timeago: ^2.0.29
  translator: ^0.1.5

dev_dependencies:
  build_runner: ^1.10.2
  flutter_sheet_localization_generator: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^0.12.2
  lint: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/flags/
    - assets/img/
    - assets/svg/
