name: vigor
description: mHealth Platform, utilizing FHIR, written in Dart/Flutter to create
  transcendent data

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.8.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  sqflite: ^1.3.1
  sembast_sqflite: ^1.0.0
  sembast: ^2.4.7+6
  path_provider: ^1.6.22
  intl: ^0.16.1
  google_fonts: ^1.1.1
  get: ^3.15.0
  translator: ^0.1.5
  freezed_annotation: ^0.12.0
  dartz: ^0.9.2
  flutter_bloc: ^6.0.6
  http: ^0.12.2
  fhir: ^0.0.10
  fhir_db: ^0.0.2
  vax_cast:
    git:
      url: git://github.com/Dokotela/vax_cast.git
      ref: vigor
  timeago: ^2.0.28
  auto_size_text: ^2.1.0
  photo_view: ^0.10.2
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.12.2
  build_runner: ^1.10.3
  lint: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/flags/
    - assets/img/
    - assets/svg/
