name: vigor
description: mHealth Platform, utilizing FHIR, written in Dart/Flutter to create transcendent data

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  sqflite: ^1.3.1
  sembast_sqflite: ^1.0.0
  sembast: ^2.4.7+4
  path_provider: ^1.6.11
  intl: ^0.16.1
  google_fonts: ^1.1.0
  get: ^3.4.1
  translator: ^0.1.5
  freezed_annotation: ^0.11.0
  dartz: ^0.9.1
  flutter_bloc: ^6.0.1
  http: ^0.12.2
  fhir:
    path: pkg/fhir_r4

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.11.4
  build_runner: ^1.10.1

flutter:
  uses-material-design: true
  assets:
    - lib/presentation/localization/lang/
    - lib/presentation/img/flags/
    - lib/presentation/img/
                                      