const vaccineList = [
  'DTaP - Diptheria, Tetanus and Pertussis',
  'Hepatitis A',
  'Haemophilus influenzae type b',
  'Hepatitis B',
  'HPV',
  'Influenza',
  'Meningococcus',
  'MMR - Measles, Mumps, and Rubella',
  'Pneumococcus (PCV 13)',
  'Pneumococcus (PPV23)',
  'Polio',
  'Rotavirus',
  'Varicella/Chicken Pox',
  'Zoster/Shingles',
];

const cvxToString = {
  '08': 'Hepatitis B',
  '20': 'DTaP - Diptheria, Tetanus and Pertussis',
  '48': 'Haemophilus influenzae type b',
  '133': 'Pneumococcus (PCV 13)',
  '10': 'Polio',
  '116': 'Rotavirus',
  '140': 'Influenza',
  '52': 'Hepatitis A',
  '03': 'MMR - Measles, Mumps, and Rubella',
  '21': 'Varicella/Chicken Pox',
  '165': 'HPV',
  '114': 'Meningococcus',
  '187': 'Zoster/Shingles',
  '33': 'Pneumococcus (PPV23)',
};

const stringToCvx = {
  'Hepatitis B': '08',
  'DTaP - Diptheria, Tetanus, and Pertussis': '20',
  'Haemophilus influenzae type b': '48',
  'Pneumococcus (PCV 13)': '133',
  'Polio': '10',
  'Rotavirus': '116',
  'Influenza': '140',
  'Hepatitis A': '52',
  'MMR - Measles, Mumps, and Rubella': '03',
  'Varicella/Chicken Pox': '21',
  'HPV': '165',
  'Meningococcus': '114',
  'Zoster/Shingles': '187',
  'Pneumococcus (PPV23)': '33',
};

const tradeNameToCvx = {
  'MENVEO': '136',
  'ACTHIB': '48',
  'ADACEL': '115',
  'Bexsero': '163',
  'BOOSTRIX': '115',
  'DAPTACEL': '106',
  'DT(GENERIC)': '28',
  'ENGERIX B-PEDS': '8',
  'ENGERIX-B-ADULT': '43',
  'Gardasil 9': '165',
  'HAVRIX-ADULT': '52',
  'HAVRIX-PEDS': '83',
  'HEPLISAV-B': '189',
  'HIBERIX': '48',
  'INFANRIX': '20',
  'IPOL': '10',
  'KINRIX': '130',
  'MENACTRA': '114',
  'MenQuadfi': '203',
  'Menveo': '136',
  'M-M-R II': '3',
  'PEDIARIX': '110',
  'PEDVAXHIB': '49',
  'PENTACEL': '120',
  'PNEUMOVAX 23': '33',
  'PREVNAR 13': '133',
  'PROQUAD': '94',
  'Quadracel': '130',
  'RECOMBIVAX-ADULT': '43',
  'RECOMBIVAX-DIALYSIS': '44',
  'RECOMBIVAX-PEDS': '8',
  'ROTARIX': '119',
  'ROTATEQ': '116',
  'SHINGRIX': '187',
  'TDVAX': '9',
  'Tenivac': '113',
  'Trumenba': '162',
  'TWINRIX': '104',
  'VAQTA-ADULT': '52',
  'VAQTA-PEDS': '83',
  'VARIVAX': '21',
  'VAXELIS': '146',
  'ZOSTAVAX': '121',
};

const tradeNames = {
  'ACTHIB',
  'ADACEL',
  'Bexsero',
  'BOOSTRIX',
  'DAPTACEL',
  'DT(GENERIC)',
  'ENGERIX B-PEDS',
  'ENGERIX-B-ADULT',
  'Gardasil 9',
  'HAVRIX-ADULT',
  'HAVRIX-PEDS',
  'HEPLISAV-B',
  'HIBERIX',
  'INFANRIX',
  'IPOL',
  'KINRIX',
  'M-M-R II',
  'MENACTRA',
  'MenQuadfi',
  'MENVEO',
  'Menveo',
  'PEDIARIX',
  'PEDVAXHIB',
  'PENTACEL',
  'PNEUMOVAX 23',
  'PREVNAR 13',
  'PROQUAD',
  'Quadracel',
  'RECOMBIVAX-ADULT',
  'RECOMBIVAX-DIALYSIS',
  'RECOMBIVAX-PEDS',
  'ROTARIX',
  'ROTATEQ',
  'SHINGRIX',
  'TDVAX',
  'Tenivac',
  'Trumenba',
  'TWINRIX',
  'VAQTA-ADULT',
  'VAQTA-PEDS',
  'VARIVAX',
  'VAXELIS',
  'ZOSTAVAX',
};
